### ISSUE TITLE
Not all rss feeds are supported?

### ISSUE THREAD

**Issue by Gargo** [kiliankoe/RSS#6]
2016-07-24 17:22:40.200 RSS_Example[29711:1066759] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.

link:
http://gargo.of.by/feed/

**Comment by kiliankoe** [comment]
I started building this library on a whim, it's not even closed to being finished yet. Please don't use it (yet).

On another note: The error you posted above has nothing to do with this or any other library. You'll get that error no matter what. It's due to the fact that you're trying to access a "non-secure" resource by not using HTTPS. You can either specify an exception in your Info.plist (see [here](https://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/) for more details) or register an SSL certificate for your domain. According to Apple iOS will be requiring SSL encryption for _any_ network call soon, so option 2 might be the better way to go.

**Comment by Gargo** [comment]
I think you should at least mention in readme that this library doesn't support RSS on http websites.

And I also don't understand what is the reason of such "security" because rss by itself is just a text file

**Comment by kiliankoe** [comment]
I'll definitely mention how to use this with HTTP endpoints once it's fully functional. But there's really nothing this library or any other library can do about that, it's something you have to configure in Xcode for your application. And once you do, everything works.
